### ISSUE TITLE
does not match the name given in the repository's definition

### ISSUE THREAD

**Issue by greatken999** [Tencent/PhoenixGo#11]
DEBUG: /home/ken/.cache/bazel/_bazel_root/d55109668bdfdb750ffd86a7a38971f1/external/bazel_tools/tools/build_defs/repo/http.bzl:63:5: patch file //third_party/tensorflow:tensorflow.patch, path /home/ken/PhoenixGo/third_party/tensorflow/tensorflow.patch
WARNING: /home/ken/.cache/bazel/_bazel_root/d55109668bdfdb750ffd86a7a38971f1/external/protobuf_archive/WORKSPACE:1: Workspace name in /home/ken/.cache/bazel/_bazel_root/d55109668bdfdb750ffd86a7a38971f1/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions

**Comment by wodesuck** [comment]
It is caused by Tensorflow. Should be fine since it just a WARNING.

**Comment by greatken999** [comment]
yes
