### ISSUE TITLE
mac support?

### ISSUE THREAD

**Issue by tigerking** [Tencent/PhoenixGo#13]
Build stops with error on MAC

bazel build //mcts:mcts_main
DEBUG: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/bazel_tools/tools/build_defs/repo/http.bzl:51:5: patch file //third_party/tensorflow:tensorflow.patch, path /Users/tk_x/workspace/myproject/trunk/go/PhoenixGo/third_party/tensorflow/tensorflow.patch
WARNING: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/protobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
DEBUG: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/bazel_tools/tools/build_defs/repo/http.bzl:51:5: patch file //third_party/glog:glog.patch, path /Users/tk_x/workspace/myproject/trunk/go/PhoenixGo/third_party/glog/glog.patch
WARNING: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/grpc/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions
WARNING: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/org_tensorflow/tensorflow/core/BUILD:1955:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/org_tensorflow/tensorflow/tensorflow.bzl:1179:30
INFO: Analysed target //mcts:mcts_main (0 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_tk_x/9c9fc22902407ae0d7f75c5052e8b3a8/external/jpeg/BUILD:269:1: C++ compilation of rule '@jpeg//:simd_armv7a' failed (Exit 1)
error: unknown target CPU 'armv7-a'
Target //mcts:mcts_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.653s, Critical Path: 0.17s
INFO: 0 processes.

**Comment by tigerking** [comment]
New issue:
looks like there are porting /config task to achieve this

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "ZeroModelBase::INPUT_DIM", referenced from:
      ZeroModel::Forward(std::__1::vector<std::__1::vector<bool, std::__1::allocator<bool> >, std::__1::allocator<std::__1::vector<bool, std::__1::allocator<bool> > > > const&, std::__1::vector<std::__1::vector<float, std::__1::allocator<float> >, std::__1::allocator<std::__1::vector<float, std::__1::allocator<float> > > >&, std::__1::vector<float, std::__1::allocator<float> >&) in libzero_model.a(zero_model.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //mcts:mcts_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3858.866s, Critical Path: 126.08s
FAILED: Build did NOT complete successfully

**Comment by wodesuck** [comment]
Fix in 4c56c322028dc98e6e1e44b0df5e8fafe32d7786, `git pull` and try again.
