### ISSUE TITLE
basic questions about compilation and running

### ISSUE THREAD

**Issue by pw31** [Tencent/PhoenixGo#17]
Could I please ask how to compile and run PhoenixGo on a simple Laptop?  My laptop is Ubuntu 14.04, processor is 4x i7-2640M CPU @ 2.80GHz. I have no GPU support under Linux.  

1) I managed to compile, but there are so many questions during config which I don't know how to 
    answer properly, mainly about Tensorflow.  I think I answered all questions with "no", and 
    it did compile.

2) How should my etc/my.config should look like? I have no clue what all these options mean.
    At the moment, when I just try 

   > bazel-bin/mcts/mcts_main --config_path=etc/mcts_dist.conf --gtp --logtostderr --v=1

It will eventually print 

    ... "MCTSEngine: waiting all eval threads init"

and then nothing happens, and I can't get it running under gogui.

Thanks!

**Comment by wodesuck** [comment]
Try sending gtp commands in command line, such as `genmove b`.

**Comment by chilin99999** [comment]
I have the same question!
OS: Ubuntu 16.04
Bazel version: 0.11.1 (I can't not compile successfully with the latest version, 0.13.0)
GPU: no (So I answered all questions with "n")

I run the command:
```
bazel-bin/mcts/mcts_main --config_path=etc/custom.conf --gtp --logtostderr --v=1
```

And it shows my config
```
max_search_tree_size: 400000000
max_children_per_node: 64
timeout_ms_per_step: 30000
eval_batch_size: 4
eval_wait_batch_timeout_us: 100
model_config {
  train_dir: "ckpt"
}
gpu_list: "0"
c_puct: 2.5
virtual_loss: 1
enable_resign: true
v_resign: -0.9
dirichlet_noise_alpha: 0.03
dirichlet_noise_ratio: 0.25
enable_background_search: true
policy_temperature: 0.67
inherit_default_act: true
early_stop {
  enable: true
  check_every_ms: 100
  sims_factor: 1
  sims_threshold: 2000
}
unstable_overtime {
  enable: true
  time_factor: 0.3
}
behind_overtime {
  enable: true
  time_factor: 0.3
}

I0515 13:39:20.816610  6848 mcts_engine.cc:85] MCTSEngine: waiting all eval threads init
I0515 13:39:20.816622  6848 mcts_engine.cc:87] MCTSEngine: all eval threads init done
```

And, then, nothing happened.
Even I try sending gtp commands, such as "list_commands" or "genmove black".

**Comment by chilin99999** [comment]
It's my custom config.
```
num_eval_threads: 0
num_search_threads: 0
max_children_per_node: 64
max_search_tree_size: 400000000
timeout_ms_per_step: 30000
max_simulations_per_step: 0
eval_batch_size: 4
eval_wait_batch_timeout_us: 100
model_config {
    train_dir: "ckpt"
    enable_tensorrt: 0
}
gpu_list: "0"
c_puct: 2.5
virtual_loss: 1.0
enable_resign: 1
v_resign: -0.9
enable_dirichlet_noise: 0
dirichlet_noise_alpha: 0.03
dirichlet_noise_ratio:  0.25
monitor_log_every_ms: 0
get_best_move_mode: 0
enable_background_search: 1
enable_policy_temperature: 0
policy_temperature: 0.67
inherit_default_act: 1
early_stop {
    enable: 1
    check_every_ms: 100
    sims_factor: 1.0
    sims_threshold: 2000
}
unstable_overtime {
    enable: 1
    time_factor: 0.3
}
behind_overtime {
    enable: 1
    act_threshold: 0.0
    time_factor: 0.3
}
```

Because I have no GPU, so I set "num_eval_threads" and "num_search_threads" to 0.

**Comment by wodesuck** [comment]
@chilin99999 no, running on CPU should also set these two options. You may try using `etc/mcts_1gpu_notensorrt.conf`, that also work with CPU.

**Comment by pw31** [comment]
@wodesuck: 
> bazel-bin/mcts/mcts_main --config_path=etc/mcts_1gpu.conf  --gtp --logtostderr --v=1

says ...

I0516 18:35:23.369431 17119 mcts_main.cc:71] load config succ: 
num_eval_threads: 1
num_search_threads: 8
max_search_tree_size: 400000000
max_children_per_node: 64
timeout_ms_per_step: 30000
eval_batch_size: 4
eval_wait_batch_timeout_us: 100
model_config {
  train_dir: "ckpt"
  enable_tensorrt: true
  tensorrt_model_path: "zero.ckpt-20b-v1.FP32.PLAN"
}
gpu_list: "0"
c_puct: 2.5
virtual_loss: 1
enable_resign: true
v_resign: -0.9
dirichlet_noise_alpha: 0.03
dirichlet_noise_ratio: 0.25
enable_background_search: true
policy_temperature: 0.67
inherit_default_act: true
early_stop {
  enable: true
  check_every_ms: 100
  sims_factor: 1
  sims_threshold: 2000
}
unstable_overtime {
  enable: true
  time_factor: 0.3
}
behind_overtime {
  enable: true
  time_factor: 0.3
}
F0516 18:35:23.384943 17119 trt_zero_model.cc:193] TensorRT is not enable!
*** Check failure stack trace: ***
*** Aborted at 1526492123 (unix time) try "date -d @1526492123" if you are using GNU date ***
PC: @                0x0 (unknown)
Abort (core dumped)

**Comment by chilin99999** [comment]
@wodesuck Thank you!! It runs successfully!!!

**Comment by wodesuck** [comment]
@pw31 You don't have TensorRT, use `mcts_1gpu_notensorrt.conf`.

**Comment by wonderingabout** [comment]
in case you need help for ubuntu, see : 

https://github.com/Tencent/PhoenixGo/issues/23#issuecomment-444374444
