### ISSUE TITLE
已经安装了Tensorflow，为啥还要编译一遍？

### ISSUE THREAD

**Issue by wordcount** [Tencent/PhoenixGo#18]
修改了Tensorflow的源码？

**Comment by wodesuck** [comment]
“安装 Tensorflow”是指安装了 Tensorflow 的 Python package，PhoenixGo 需要 Tensorflow 的 C++ library.

**Comment by wordcount** [comment]
那样的话，似乎也能以依赖的方式解决。
tensorflow自身支持打包成so文件和头文件的方式供其他项目使用，找到了下面这个issue：
https://github.com/tensorflow/tensorflow/issues/2412

**Comment by wodesuck** [comment]
我看过这个 issue，没找到有打包好的 so 可以下载。

**Comment by guotong1988** [comment]
same question
