### ISSUE TITLE
在mac上编译出错，能看一下问题出在哪里吗？

### ISSUE THREAD

**Issue by SidXu** [Tencent/PhoenixGo#19]
(virtual) ➜  PhoenixGo git:(master) bazel build //mcts:mcts_main                                                    
WARNING: /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/protobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
WARNING: /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/org_tensorflow/tensorflow/core/BUILD:1955:1: in includes attribute of cc_library rule @org_tensorflow//tensorflow/core:framework_headers_lib: '../../../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'external/org_tensorflow/tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/org_tensorflow/tensorflow/tensorflow.bzl:1179:30
WARNING: /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/grpc/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/grpc/WORKSPACE (@com_github_grpc_grpc) does not match the name given in the repository's definition (@grpc); this will cause a build error in future versions
INFO: Analysed target //mcts:mcts_main (1 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_xutao/ee4217f9ef26aaefbb212a4e6228709a/external/jpeg/BUILD:269:1: C++ compilation of rule '@jpeg//:simd_armv7a' failed (Exit 1)
error: unknown target CPU 'armv7-a'
Target //mcts:mcts_main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.848s, Critical Path: 0.14s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by SnowWalkerJ** [comment]
I am facing with a similar situation. Have you worked this out?
