### ISSUE TITLE
will this project release a windows version

### ISSUE THREAD

**Issue by l1t1** [Tencent/PhoenixGo#20]
if it can't be used easily, and it's weaker than leelaz+elf weight, no  appeal.

**Comment by baicaigithub** [comment]
Doesn't this engine win a contest recently? Do you have data to show the comparison between the two?

**Comment by wodesuck** [comment]
Work in progress. It's not easy to build Tensorflow on Windows.

**Comment by godmoves** [comment]
A [reference](https://joe-antognini.github.io/machine-learning/windows-tf-project) for you. I am too busy to work this out : )

PS: I've tried bazel for WIn but failed : \

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
can use openblas instread?

**Comment by l1t1** [comment]
ref https://www.zhihu.com/question/52122520

**Comment by wodesuck** [comment]
We have built windows version successfully. A pre-built binary will be released soon after some packaging work and compatibility test.
