### ISSUE TITLE
系统macos，怎么使用sabaki显示gui界面，输入play后报错

### ISSUE THREAD

**Issue by hj456992** [Tencent/PhoenixGo#21]
![image](https://user-images.githubusercontent.com/22442849/40102210-792d2714-591c-11e8-9666-2cccaf9f5891.png)

**Comment by wodesuck** [comment]
`play` 之后应该有颜色和位置，比如`play b Q16`。

Sabaki 在 Engines -> Manage Engines 里设置启动 GTP Engine 的命令（填入 path 和 arguments），然后 Engines -> Attach 加载。

**Comment by hj456992** [comment]
谢谢，加上了颜色和位置之后不报错了
Engines -> Manage Engines这个文件路径在哪里？我项目里没有找到

**Comment by wodesuck** [comment]
我指的是 Sabaki 的菜单

**Comment by wodesuck** [comment]
path `{project-root}/bazel-bin/mcts/mcts_main`
arguments `--config_path=etc/{config} --gtp --logtostderr --v=1`
