### ISSUE TITLE
Workaround on issues with sabaki

### ISSUE THREAD

**Issue by baicaigithub** [Tencent/PhoenixGo#22]
Sabaki is a very good looking UI. However I do encounter some issues with this appimage app.

1. Current working dir
I assume the working dir for Sabaki is not the same as the PhoneixGo, which causes errors like config not found, and another file not found which is not passed through by argument. My solution is to use a script that wraps the binary.
```
#!/bin/bash
cd "$(dirname "$0")"
pwd
bazel-bin/mcts/mcts_main --config_path=etc/mcts_1gpu_notensorrt.conf --gtp --logtostderr --v=1
```
2. Sabaki hangs without debug output, when the option 'start after attach' is chose.
Turn off that option and use 'Engines - Generage Move' to start a move for black.

Ok. Now PhoneixGo works for me and I'll try it with online go games.

**Comment by wodesuck** [comment]
Great guide. I have referred this issue in README.
