### ISSUE TITLE
The engine plan file is not compatible with this version of GIE, please rebuild.

### ISSUE THREAD

**Issue by Godady** [Tencent/PhoenixGo#23]
After configued Tensorrt. I got PhoenixGo run in my Ubuntu 18.04 without Tensorrt enabled(using mcts_1gpu_notensorrt.conf), but I couldn't get it run under  Tensorrt enabled(using mcts_1gpu.conf). I always got the message "The engine plan file is not compatible with this version of GIE, please rebuild.".
My software configuration is: Ubuntu 18.04, CUDA 9.0, Cudnn 7.0.5, Bazel 0.11, Tensorrt 3.04, default python 2.7. and i select GCC-6 as the compiler. The one thing i got messed is i firstly installed Tensorrt 4.0.1, and i got the message saying "The engine plan file is not compatible with this version of GIE". Then I tried hard to remove tensorrt 4.0.1 and reinstalled tensorrt 3.04 through dpkg command. I had learned that  tensorrt 3.04 can only successfully installed by tar file but not deb file. So ,could you give me any suggestion how to get tensorrt worked. Many thanks!

**Comment by samecos** [comment]
I think you might try using py=3.6 more effectively for your Compiled.

**Comment by wodesuck** [comment]
Have you rebuilt Phoenix (also re-run `./configure`) after reinstalled TensorRT?

Actually, you only need to unarchive TensorRT tarball to any path, and specify in `./configure`. (and maybe need to add `{TensorRT}/lib` to `LD_LIBRARY_PATH`)

**Comment by Godady** [comment]
i got it. The trick is you should install tensorrt through tar file.

**Comment by wonderingabout** [comment]
no, i installed tensorrt 3.0.4 on ubuntu 16.04 via deb file (installed cuda 9.0 and cudnn 7.0 via deb file too) and it works, engine plays games successfully with tensorRT

**Comment by wonderingabout** [comment]
i will try with tensoRT 5 and tensort RT 4 and let you all know if it is compatible (deb install, ubuntu 16.04, cuda 9.0, cudnn 7.0.5)
