### ISSUE TITLE
Is there any way to load sgf?

### ISSUE THREAD

**Issue by chilin99999** [Tencent/PhoenixGo#24]
OS: Ubuntu 16.04

I have compiled an executable, and run successfully.
But... Is there any way to load sgf?
I enter "list_commands" in GTP mode, but there's no "loadsgf".
```
version
list_commands
quit
clear_board
boardsize
komi
time_settings
time_left
place_free_handicap
set_free_handicap
play
genmove
final_score
get_debug_info
get_last_move_debug_info
```

In Readme.md "Command Line Options",
there's a "--init_moves" option.
But I don't know how to do with it.
I have tried "--init_moves (;SZ[19];B[pd];W[dp];B[qp];W[dd];B[oq])" and "--init_moves xxx.sgf",
but it can't work correctly.

**Comment by wodesuck** [comment]
Not support sgf yet. `--init_move` format in `--init_move=pd,dp,qp,oq`, you may do a simple convertion from sgf.

**Comment by chilin99999** [comment]
@wodesuck Ok, thank you!!
