### ISSUE TITLE
How to compile a static excutable for other linux system?

### ISSUE THREAD

**Issue by chilin99999** [Tencent/PhoenixGo#25]
Follow the compiling guide can make an executable.
The executable "mcts_main" is not in the PhoenixGo folder.
If I copy it into PhoenixGo folder and execute it, a error will happened.
```
./mcts_main: error while loading shared libraries: libtensorflow_framework.so: cannot open shared object file: No such file or directory
```

But I need to run it in other linux system without these libraries.
What can I do?
Is there any way to build a static executable for system that doesn't install these libraries?

**Comment by wodesuck** [comment]
`libtensorflow_framework.so` exist at `bazel-bin/external/org_tensorflow/tensorflow`.

I have try building a static one, but seems difficult to static link all Tensorflow dependices

**Comment by godmoves** [comment]
Use this command `bazel build --config=monolithic //mcts:mcts_main`, then the compiler will try to link everything together. Hope it work for you.

**Comment by chilin99999** [comment]
@godmoves :

> bazel build --config=monolithic //mcts:mcts_main

I tried this command to compile executable,
but it can not execute correctly.
```
F external/org_tensorflow/tensorflow/core/framework/function.cc:1328] Check failed: GetOpGradFactory()->insert({op, func}).second Duplicated gradient for MapAccumulate
Aborted (core dumped)
``` 

Is there any way to solve that?

**Comment by godmoves** [comment]
@chilin99999 Seems you don't use GPU? Maybe you should modify the config file and set GPU list to "".

**Comment by wodesuck** [comment]
`gpu_list` won't be the problem, it should be ignored on CPU machine.

I have try `monolithic` and cannot run either (and still found `libtensorflow_framework.so` in `ldd mcts_main`...). maybe `monolithic` is still bugly.

**Comment by godmoves** [comment]
This command may not work for this repo : (

**Comment by chilin99999** [comment]
Oh.... : (
Even if this problem cannot be solved, I am still very grateful to you.
Thanks!
Should I close this issue?
