### ISSUE TITLE
ubuntu 16.04 下sabaki设置问题

### ISSUE THREAD

**Issue by vivwangsc** [Tencent/PhoenixGo#28]
谢谢凤凰围棋团队的努力付出。

我想在ubuntu下使用sabaki测试对局，
路径是：/home/wsc/PhoenixGo/bazel-bin/mcts/mcts_main
参数是：--config_path=/home/wsc/PhoenixGo/etc/mcts_1gpu_notensorrt.conf --gtp --logtostderr --v=1
然而出现错误信息：E0519 12:43:54.538918 29392 checkpoint_utils.cc:33] Error reading "ckpt/checkpoint": No such file or directory [2]

直接在PhoenixGo目录下执行/home/wsc/PhoenixGo/bazel-bin/mcts/mcts_main --config_path=/home/wsc/PhoenixGo/etc/mcts_1gpu_notensorrt.conf --gtp --logtostderr --v=1
就没有问题，但不在PhoenixGo目录下执行程序就报上面但错误？

请问是否有训练文件路径的设置参数？

**Comment by vivwangsc** [comment]
已经在配置文件中找到设置，已经解决

**Comment by wonderingabout** [comment]
on windows if you run mcts_main.exe directly : 
you need to specify .conf file path using the c:/users/ format and not c:\users\

for example : 
 in : 
`C:\Users\hello2\AppData\Roaming\npm\node_modules\gtp2ogs\bin\mcts_main.exe --gtp --config_path C:\Users\hello2\AppData\Roaming\npm\node_modules\gtp2ogs\etc\mcts_1gpu_notensorrt.conf`

go at line (inside the .conf file) :
```
model_config {
    train_dir: "c:/Users/hello2/AppData/Roaming/npm/node_modules/gtp2ogs/etc/ckpt"
}
```
 
full file conf example : 
```
num_eval_threads: 1
num_search_threads: 64
max_children_per_node: 512
max_search_tree_size: 400000000
timeout_ms_per_step: 5000
max_simulations_per_step: 0
eval_batch_size: 64
eval_wait_batch_timeout_us: 5000
model_config {
    train_dir: "c:/Users/hello2/AppData/Roaming/npm/node_modules/gtp2ogs/etc/ckpt"
}
gpu_list: "0"
c_puct: 2.5
virtual_loss: 1.0
enable_resign: 1
v_resign: -0.9
enable_dirichlet_noise: 0
dirichlet_noise_alpha: 0.03
dirichlet_noise_ratio:  0.25
monitor_log_every_ms: 0
get_best_move_mode: 0
enable_background_search: 1
enable_policy_temperature: 0
policy_temperature: 0.67
inherit_default_act: 1
early_stop {
    enable: 1
    check_every_ms: 1000
    sims_factor: 1.0
    sims_threshold: 45000
}
unstable_overtime {
    enable: 0
    time_factor: 0.3
}
behind_overtime {
    enable: 0
    act_threshold: 0.0
    time_factor: 0.3
}
time_control {
    enable: 0
    c_denom: 40
    c_maxply: 120
    reserved_time: 10.0
}

```
