### ISSUE TITLE
关于对gpu的需求的疑问

### ISSUE THREAD

**Issue by 782832949** [Tencent/PhoenixGo#3]
贴个腾讯PhoenixGo的链接：http://tech.qq.com/a/20180511/024785.htm
这个新闻说只要1块GPU就够了？！是指训练用1块就够了还是跑训练好的模型用1块？

**Comment by GenjiWu** [comment]
....当然是跑模型了

**Comment by FeelF** [comment]
当然指跑训练好的模型，他没有开源训练源码，你是没有办法训练的。

**Comment by diadorak** [comment]
自对弈一块gpu跑1000年

**Comment by DeepinW** [comment]
训练的话你得有微信后台这么多的机器，用它们的闲时计算资源。这种资源对于个人玩家来说，根本玩不起。
