### ISSUE TITLE
question about FeatherCNN and ncnn

### ISSUE THREAD

**Issue by l1t1** [Tencent/PhoenixGo#31]
https://github.com/Tencent/FeatherCNN says it  is a high performance inference engine for convolutional neural networks, https://github.com/Tencent/ncnn says it is a high-performance neural network inference framework optimized for the mobile platform, and they both spports ARM.
will PhoenixGo  run on ARM equipment too in the future?

**Comment by wodesuck** [comment]
No plan for ARM yet.

**Comment by l1t1** [comment]
thanks
