### ISSUE TITLE
LeelaZero + PhoenixGo's weights

### ISSUE THREAD

**Issue by yenw** [Tencent/PhoenixGo#35]
* Source Code
  * https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leela-zero-0.14-phoenix-go.zip
* Weights
  * V1: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/PhoenixGo_v1.txt.gz
* Leela Zero
  * Windows
    * CPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_win_x86_cpu.exe.zip
    * GPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_win_x86_gpu_opencl.exe.zip
  * Linux
    * CPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_linux_x64_cpu.zip
    * GPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_linux_x64_gpu_opencl.zip
  * MacOS
    * CPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_mac_x64_cpu.zip
    * GPU: https://github.com/yenw/LeelaZero_PhoenixGo/releases/download/v1/leelaz_mac_x64_gpu_opencl.zip

**Comment by wodesuck** [comment]
Thank you for your contribution.
