### ISSUE TITLE
Errors occurred when building origin master's .sln by VS2015

### ISSUE THREAD

**Issue by fmxFranky** [Tencent/PhoenixGo#37]
I have tried to build the .sln used VS2015 but the builder occurs the errors followed:
1>------ 已启动全部重新生成: 项目: mcts_main, 配置: Release x64 ------
1>  Performing Protoc Build Tools
1>  Performing Protoc Build Tools
1>  Performing Protoc Build Tools
1>  Performing Protoc Build Tools
1>  Performing Protoc Build Tools
1>  go_comm.cc
1>  go_state.cc
1>  str_utils.cc
1>  thread_conductor.cc
1>  timer.cc
1>  wait_group.cc
1>  async_dist_zero_model_client.cc
1>  dist_config.pb.cc
1>  dist_zero_model.grpc.pb.cc
1>  dist_zero_model.pb.cc
1>  dist_zero_model_client.cc
1>  leaky_bucket.cc
1>  byo_yomi_timer.cc
1>  mcts_config.cc
1>  mcts_config.pb.cc
1>  mcts_debugger.cc
1>  mcts_engine.cc
1>  mcts_main.cc
1>  mcts_monitor.cc
1>  checkpoint_state.pb.cc
1>  正在生成代码...
1>  正在编译...
1>  checkpoint_utils.cc
1>  model_config.pb.cc
1>  trt_zero_model.cc
1>  zero_model.cc
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(77): warning C4005: “LOG”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(506): note: 参见“LOG”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(86): warning C4005: “VLOG_IS_ON”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/vlog_is_on.h(93): note: 参见“VLOG_IS_ON”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(91): warning C4005: “VLOG”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(1094): note: 参见“VLOG”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(99): warning C4005: “CHECK”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(586): note: 参见“CHECK”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(246): warning C4005: “CHECK_OP_LOG”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(749): note: 参见“CHECK_OP_LOG”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(248): warning C4005: “CHECK_OP”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(764): note: 参见“CHECK_OP”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(251): warning C4005: “CHECK_EQ”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(788): note: 参见“CHECK_EQ”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(252): warning C4005: “CHECK_NE”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(789): note: 参见“CHECK_NE”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(253): warning C4005: “CHECK_LE”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(790): note: 参见“CHECK_LE”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(254): warning C4005: “CHECK_LT”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(791): note: 参见“CHECK_LT”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(255): warning C4005: “CHECK_GE”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(792): note: 参见“CHECK_GE”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(256): warning C4005: “CHECK_GT”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(793): note: 参见“CHECK_GT”的前一个定义
1>D:\kz\tensorflow\tensorflow/core/platform/default/logging.h(259): warning C4005: “CHECK_NOTNULL”: 宏重定义
1>  D:\kz\glog-0.3.5\glog/logging.h(799): note: 参见“CHECK_NOTNULL”的前一个定义
1>  正在生成代码...
1>    正在创建库 D:\PhoenixGo-master\x64\Release\mcts_main.lib 和对象 D:\PhoenixGo-master\x64\Release\mcts_main.exp
1>mcts_debugger.obj : error LNK2001: 无法解析的外部符号 "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
1>mcts_engine.obj : error LNK2001: 无法解析的外部符号 "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
1>mcts_monitor.obj : error LNK2001: 无法解析的外部符号 "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
1>tf_core_lib.lib(numbers.obj) : error LNK2019: 无法解析的外部符号 "public: double __cdecl double_conversion::StringToDoubleConverter::StringToDouble(char const *,int,int *)const " (?StringToDouble@StringToDoubleConverter@double_conversion@@QEBANPEBDHPEAH@Z)，该符号在函数 "bool __cdecl tensorflow::strings::safe_strtod(char const *,double *)" (?safe_strtod@strings@tensorflow@@YA_NPEBDPEAN@Z) 中被引用
1>tf_core_lib.lib(numbers.obj) : error LNK2019: 无法解析的外部符号 "public: float __cdecl double_conversion::StringToDoubleConverter::StringToFloat(char const *,int,int *)const " (?StringToFloat@StringToDoubleConverter@double_conversion@@QEBAMPEBDHPEAH@Z)，该符号在函数 "unsigned __int64 __cdecl tensorflow::strings::FloatToBuffer(float,char *)" (?FloatToBuffer@strings@tensorflow@@YA_KMPEAD@Z) 中被引用
1>D:\PhoenixGo-master\x64\Release\mcts_main.exe : fatal error LNK1120: 3 个无法解析的外部命令
========== 全部重新生成: 成功 0 个，失败 1 个，跳过 0 个 ==========

Firstly,i am confused that how to make the" tensorflow logging glog redefined warnings "  disappeared
Secondly, after i changed the thirdparty.props for adapt the packages' build/source paths,the errors LINK2001 still exits. I think the reason the the errors occurred may be some lib including missing error.And Who can tell me how can i fix the problem?
thx~

**Comment by wodesuck** [comment]
I guess the reason of errors is that you didn't build glog with gflags support. I haven't found way to disappear warnings either, ignore them.

BTW, there is prebuilt binary for Windows already.

**Comment by fmxFranky** [comment]
@wodesuck  thx for you suggestion.
 In fact, i have build glog and gflags on my win7 x64 computer before build the project.And as the same as the projects's "Thirdparty.prop", i put the glog,gflag,boost folders into an tree folder and set the build paths correctly.
So i think perhaps there are some errors in  building source code of gflags and glog. And i will check the folders or rebuild the glog and gflags.
On the other hand, i am curious about do you try that using vs2015's nuget installing the glags and glog? 
I am appreciate if you can tell me if there are some important points in building glog gflags form source code. thanks alot!

**Comment by wodesuck** [comment]
Have you specified `gflags_DIR` when cmake glog?

I have tried nuget, but surprisingly found the package glog and gflags don't support vs 2015...

**Comment by fmxFranky** [comment]
After rebuilding glog and gflags, the errors above are disappeared, only redefined warnings and some new warnings for "libpng12_static.lib(png.obj) : warning LNK4217: 本地定义的符号 xxx 在函数 yyy_xxx 中导入" alive, and the project are still be building, maybe it will succ this time~
thx~
