### ISSUE TITLE
Win GPU v1 Start doesn't work

### ISSUE THREAD

**Issue by baduk1** [Tencent/PhoenixGo#38]
After installing Visual C++ Redistributable for Visual Studio 2015 (the file name is vc_redist.x64.exe) - as suggested in PDF guide, same XXX.dll pop-up appears. How to solve this? Thanks 
P.S. CPU version works perfectly.

**Comment by wodesuck** [comment]
Please tell me what XXX.dll is..

**Comment by baduk1** [comment]
@wodesuck cufff64_90.dll

**Comment by wodesuck** [comment]
You should install cuda & cudnn. Btw, it is cufft64_90.dll, I guess.

**Comment by baduk1** [comment]
I installed cuda and cudnn as in instruction.

**Comment by wodesuck** [comment]
Try adding them in your PATH

**Comment by l1t1** [comment]
copy the dlls to bin directory, just as https://github.com/Tencent/PhoenixGo/issues/36

**Comment by baduk1** [comment]
I can't find that particular dll. Can you give a link or send me directly?

**Comment by l1t1** [comment]
download the cuda & cudnn as install.pdf said, then unzip them,you will found dlls

**Comment by wodesuck** [comment]
Default installed in `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin`.

**Comment by baduk1** [comment]
@wodesuck  https://imgur.com/a/eLQjyNl

**Comment by wodesuck** [comment]
I think you hadn't installed cuda...

**Comment by baduk1** [comment]
@wodesuck https://imgur.com/a/hsd4si6 failed 4 times. I installed VS 2017 also

**Comment by wodesuck** [comment]
You should install cuda **9.0**.

**Comment by baduk1** [comment]
@wodesuck https://imgur.com/a/GO5O8Hw I tried sevelar times already CUDA 9 as was written in PDF

**Comment by wodesuck** [comment]
So, you should ask help from cuda community.

**Comment by l1t1** [comment]
install is not needed, unzip is ok

**Comment by wodesuck** [comment]
@l1t1 For cudnn, unzip is ok, but for cuda, I guess "install" is needed.

**Comment by l1t1** [comment]
@wodesuck not really, my nivida directory
```
 C:\Program Files (x86)\NVIDIA Corporation 的目录

2018/05/07  14:49    <DIR>          .
2018/05/07  14:49    <DIR>          ..
2018/05/07  14:48    <DIR>          3D Vision
2018/05/07  14:47    <DIR>          coprocmanager
2018/05/07  14:47    <DIR>          Display.NvContainer
2018/05/07  14:48    <DIR>          NvBackend
2018/05/07  14:48    <DIR>          NvContainer
2018/05/07  14:47    <DIR>          NvFBC
2018/05/07  14:48    <DIR>          NVIDIA GeForce Experience
2018/05/07  14:48    <DIR>          NvNode
2018/05/07  14:48    <DIR>          NvStreamSrv
2018/05/07  14:48    <DIR>          NvTelemetry
2017/08/17  20:00    <DIR>          PhysX
2018/05/07  14:49    <DIR>          ShadowPlay
2018/05/07  14:48    <DIR>          Update Core
               0 个文件              0 字节
              15 个目录  
```
see https://github.com/Tencent/PhoenixGo/issues/36

**Comment by baduk1** [comment]
I used 7Z to extract 4 missing DLLS and added them to PhoenixGo - Bin (I was confusing it with Nvidia - Cuda - Bin). Cudnn installation was no problems. Finally all working. I am not sure that Phoenix can see both of my GPUs thought. Also I did not any weights to Sabaki, as I can't find txt of Phoenix weights. I never used Sabaki before, so I wrote this: https://imgur.com/a9qarfy and they are playing now C:\Users\Admin\Desktop\2018-05-30 20_28_38-Sabaki.png  Thanks for help. If you can comment abought weights and tuning - will be appreciated.

**Comment by l1t1** [comment]
Phoenix weights includes many files , which are all in ckpt directory. so it use .conf file.

**Comment by wodesuck** [comment]
You may use `nvidia-smi` to check your gpu usage.

**Comment by baduk1** [comment]
@wodesuck are you planning to release PhoenixGo 40B? 20B is weaker than ELF on my PC.
