### ISSUE TITLE
Does the project support mac/OSX system?

### ISSUE THREAD

**Issue by qcgm1978** [Tencent/PhoenixGo#4]
I see the README file doesn't introduce the installation in the Mac system. Dose it support the OSX system?

**Comment by wodesuck** [comment]
You may try building with bazel as the same way on Linux. But since neither Tensorflow nor TensorRT provide GPU support on macOS, you could only run it slowly on CPU even you have built it successfully.

**Comment by qcgm1978** [comment]
Ok Thank your answer.
