### ISSUE TITLE
Strength + disable resign below 5%

### ISSUE THREAD

**Issue by baduk1** [Tencent/PhoenixGo#46]
What can I change to disable early resign on handicap and put max power? 
My current settings are for 2 GPU: 
num_eval_threads: 2
num_search_threads: 12
max_children_per_node: 128
max_search_tree_size: 800000000
timeout_ms_per_step: 60000
max_simulations_per_step: 0
eval_batch_size: 4
eval_wait_batch_timeout_us: 100
model_config {
    train_dir: "ckpt"
}
gpu_list: "0,1"
c_puct: 2.5
virtual_loss: 1.0
enable_resign: 1
v_resign: -0.9
enable_dirichlet_noise: 0
dirichlet_noise_alpha: 0.03
dirichlet_noise_ratio:  0.25
monitor_log_every_ms: 0
get_best_move_mode: 0
enable_background_search: 0
enable_policy_temperature: 0
policy_temperature: 0.67
inherit_default_act: 1
early_stop {
    enable: 1
    check_every_ms: 100
    sims_factor: 1.0
    sims_threshold: 2000
}
unstable_overtime {
    enable: 1
    time_factor: 0.3
}
behind_overtime {
    enable: 1
    act_threshold: 0.0
    time_factor: 0.3
}
time_control {
    enable: 1
    c_denom: 20
    c_maxply: 40
    reserved_time: 1.0
}﻿

**Comment by Splee99** [comment]
Max_search_tree_size depends on your graphic memory. Currently your setting is 800M. I think you can safely double it or even more.

**Comment by baduk1** [comment]
@Splee99  Thank you, I changed to 2000M (higher doesn't work)
Also I changed max_children_per_node: 128 to 512M 
When ELF is thinkking GPU shows 21-25% on both videocards
When PhoenixGo thinks GPU shows only 2-4% on both videocards. What else can I do to make it higher?

**Comment by Splee99** [comment]
I guess the max_children_per_node doesn't matter because it never gets that high anyway. You may want to download GPU-Z to find out real GPU usage. Mine shows about 83% for Phoenixgo vs 95% for LZ. I think that is because of the tensorflow. Using tensorrt will make the usage higher.

**Comment by Splee99** [comment]
By the way I tried to set enable_policy_temperature to 1. Not sure if that is related but the resulting Phoenixgo seems to be stronger than ELF because of the higher usage of graphic memory. I have to test more.

**Comment by baduk1** [comment]
Did you restrict thinking for both during opponent's time?

**Comment by Splee99** [comment]
Yes I set the pondering off. However the graphic memory is never released by Sabaki so for the player using lots of graphic memory that would save a lot of data transfer time.

**Comment by baduk1** [comment]
I tried temperature 1, but ELF still won. 10 sec/move http://eidogo.com/#18m7fdAiY

**Comment by Splee99** [comment]
Yeah you're right. Initially the winrate of Phoenix go was so high, but then ELF eventually won.

**Comment by Splee99** [comment]
For handicap games, you can adjust virtual_loss. I don't know the best value yet, but after I changed it from 1.0 to 0.75, it won a 2h game with leela (non-zero version). That makes it little more optimistic during the handicap play. Further you may change the V_resign from 0.9 to 0.95. Phoenixgo can not give 2 handicaps to leela zero, at least on my computer.

**Comment by baduk1** [comment]
I changed virtual loss to 0.5 and tested 2 stones with LZ 153. PhGo played ladder https://imgur.com/HLR6pEO 
how to avoid it? 
What is a virtual loss? How is 0.75 different from 0.5?

**Comment by Splee99** [comment]
I tried virtual_loss 0.5 too. It makes PhGo taking too much risk resulting a number of dead groups. 0.75 or 0.8 is OK.

**Comment by Splee99** [comment]
Also maybe PhGo is not really two stone stronger than LZ.

**Comment by baduk1** [comment]
Yes, I am sure PhGo is not 2 stones stronger than LZ, but that should not affect ladders anyway.

**Comment by Splee99** [comment]
After recent training, LZ 157 seems to be stronger than PHgo.
