### ISSUE TITLE
Can't install PhoenixGo on osx

### ISSUE THREAD

**Issue by shounanace** [Tencent/PhoenixGo#48]
os10.13.4
iMac mid2011

here is my Term Message, it looks failure.

Macde-iMac:PhoenixGo mac$ sh -x  start.sh
++ dirname start.sh
+ cd .
+ export LD_LIBRARY_PATH=:/Users/mac/Downloads/PhoenixGo/solib
+ LD_LIBRARY_PATH=:/Users/mac/Downloads/PhoenixGo/solib
+ ./bin/mcts_main --config_path=etc/mcts_1gpu_notensorrt.conf --gtp --v=1 --log_dir=log
start.sh: line 4: 44510 Illegal instruction: 4  ./bin/mcts_main --config_path=etc/mcts_1gpu_notensorrt.conf --gtp --v=1 --log_dir=log
Macde-iMac:PhoenixGo mac$

**Comment by wodesuck** [comment]
Try this one: https://github.com/Tencent/PhoenixGo/releases/download/PhoenixGo-mac-x64-cpuonly-v1.1/PhoenixGo-mac-x64-cpuonly-v1.1-noavx2-nofma.tgz

**Comment by shounanace** [comment]
fixed, Thank you.
