### ISSUE TITLE
It's too hard to get tensorrt enabled in ubuntu.

### ISSUE THREAD

**Issue by Godady** [Tencent/PhoenixGo#49]
I've installed PhoenixGo for several PCs with different os and different gpu cards. But  every time it's like a blind torture and i had to try different settings to make tensorrt runnable. Sometimes it can be build ok, but would crashed just after initilization. For now, I could run phoenixgo with tensorrt enabled on ubuntu 1701 1804 with only tensoort-3.0.4 installed by tar file using geforce 10XX gpus. These two days I have been trying make it work on a ubuntu1804 pc with titan V gpu. I failed and I think the most newly code has some problem, coz when I built code of one month ago, it can pass the buiding, just crahed in running, but if i use  most newly code, it always says some .o files not created and failed at link stage whatever I change the gcc or reinstall different drivers.
Although I have managed to make tensorrt work, I still want the authorcould  give a general software  instruction about software config.  And could anyone tell me whether or what settings can make tensorrt run.

**Comment by wodesuck** [comment]
Could you provide some error logs?

**Comment by godmoves** [comment]
Titian V doesn't support tensorrt well and I have met the same problem before.

**Comment by wonderingabout** [comment]
in case you need help, see : 

https://github.com/Tencent/PhoenixGo/issues/23#issuecomment-444374444
