### ISSUE TITLE
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by greatken999** [Tencent/PhoenixGo#5]
bazel build //mcts:mcts_main
DEBUG: /home/ken/.cache/bazel/_bazel_ken/2b61279c4add7e259b51cb073b48b292/external/bazel_tools/tools/build_defs/repo/http.bzl:63:5: patch file //third_party/tensorflow:tensorflow.patch, path /mnt/ken-volume/Downloads/PhoenixGo/third_party/tensorflow/tensorflow.patch
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/v1.7.0.tar.gz] to /home/ken/.cache/bazel/_bazel_ken/2b61279c4add7e259b51cb073b48b292/external/org_tensorflow/v1.7.0.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/v1.7.0.tar.gz] to /home/ken/.cache/bazel/_bazel_ken/2b61279c4add7e259b51cb073b48b292/external/org_tensorflow/v1.7.0.tar.gz: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
INFO: Elapsed time: 16.168s
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by godmoves** [comment]
I think this seems a net connection issue, maybe you should try to build it again.

**Comment by wodesuck** [comment]
Bazel will download dependencies while building, so you should make sure the network of building environment is able to download them.

**Comment by greatken999** [comment]
network is ok .i can download v1.7.0.tar.gz us wget.

**Comment by wodesuck** [comment]
Found two similar issues for you https://github.com/bazelbuild/bazel/issues/4332 and https://github.com/tensorflow/tensorflow/issues/4999. You may try this solution:

```
$ sudo apt-get install ca-certificates-java
$ sudo update-ca-certificates -f
$ bazel shutdown
```

**Comment by wodesuck** [comment]
It is a bazel-related problem, you may issue them.

**Comment by wodesuck** [comment]
Btw, what is your bazel version? Bazel 0.11.1 with embedded JDK is known-good, have a try:

```
$ wget https://github.com/bazelbuild/bazel/releases/download/0.11.1/bazel-0.11.1-installer-linux-x86_64.sh
$ chmod +x bazel-0.11.1-installer-linux-x86_64.sh
$ ./bazel-0.11.1-installer-linux-x86_64.sh --user
$ export PATH="$PATH:$HOME/bin"
```

**Comment by greatken999** [comment]
fix by follow step:
1,download oracle jre
2,cp -i /path/to/oracle-jdk/jre/lib/security/cacerts /etc/ssl/certs/java
3.reboot system

thanks @wodesuck
