### ISSUE TITLE
@org_tensorflow//tensorflow/core/kernels:svd_op

### ISSUE THREAD

**Issue by zj28288322** [Tencent/PhoenixGo#50]
why i was stopped in this thing?
when bazel build //mcts:mcts_main
[1,030 / 1,032] @org_tensorflow//tensorflow/core/kernels:svd_op; 1013s local
and it stopped

**Comment by wodesuck** [comment]
Use `--verbose_failures` to get more information.

Btw, you may try building tensorflow individually. If it's a tf building problem, then you should ask help from tf community.
