### ISSUE TITLE
关于程序循环，高CPU占用的问题

### ISSUE THREAD

**Issue by SilverLeaves** [Tencent/PhoenixGo#51]
在windows运行时，发现即使不做任何操作，CPU占用会到达100%...。
在检查了程序循环代码后，发现GTPServing函数里while循环存在一些问题。
std::getline这个函数在成功后返回字节数，失败后直接返回-1，即都是真（参考：https://baike.baidu.com/item/getline%E5%87%BD%E6%95%B0/3932106?fr=aladdin）。
然后问题出现了，程序在没有输入的时候，程序并不会阻塞，仍旧会不断的轮询并且不会主动释放CPU执行时间，造成大量无谓的CPU占用。

"./mcts/mcts_main.cc"

`void GTPServing(std::istream &in, std::ostream &out)
{
    std::string cmd, output;
    ... 这里存在问题 ...
    while (std::getline(in, cmd)) {
        ...  ...
        std::tie(succ, output) = GTPExecute(*engine, cmd);
        ...  ...
        if (cmd.find("quit") != std::string::npos) {
            break;
        }
    }
    LOG(WARNING) << "exiting gtp serving";
}`

**Comment by SilverLeaves** [comment]
![snipaste_2018-07-01_00-35-50](https://user-images.githubusercontent.com/31165554/42127197-bda3fc1a-7cc6-11e8-8bc3-41d11de42959.png)

**Comment by SilverLeaves** [comment]
简单点，弄个std::cin阻塞型的函数获取输入？

**Comment by wodesuck** [comment]
你搞错了……
`std::getline` 返回的是 stream 对象： https://en.cppreference.com/w/cpp/string/basic_string/getline 。
CPU 占用是因为开了后台搜索，你把配置里的 `enable_background_search` 设成 0 就不会占用了。

**Comment by SongSinGin** [comment]
生手请教：
能否具体描述如何设置 enable_background_search 0 在何处输入？
以及缩短每手棋时间 timeout_ms_pre_step: 1,000 等等…（在视窗系统中）
完全不懂，但是可以感觉整个系统运行变得很慢…
