### ISSUE TITLE
A seemingly very effective approach to handicap games

### ISSUE THREAD

**Issue by alreadydone** [Tencent/PhoenixGo#53]
See https://github.com/gcp/leela-zero/issues/1599#issuecomment-402858323. The latest news is that it won 5 and 6-stone handicap games against a Tygem 8d 弈城8段 (latest two games in https://www.gokgs.com/gameArchives.jsp?user=baymax). The idea is just to use the color plane inputs for komi information as in https://github.com/gcp/leela-zero/compare/next...alreadydone:patch-16, and dynamically adjust komi during the game to keep the winrate within a certain range (5-12% in my implementation to make the play aggressive).
Would you try to implement it and test the effect? As far as I know PhoenixGo isn't playing handicap games on Fox, but Fine Art is, and it's reported that they are bugged by the low initial winrate problem, so please spread the words when appropriate. PhoenixGo itself is also one of the strongest bots and definitely in the position of testing this. According to https://github.com/Chicoryn/dream-go/issues/25#issuecomment-402564306, my approach should work granted that the network isn't too overfitted.

**Comment by croosn** [comment]
https://github.com/gcp/leela-zero/issues/1599#issuecomment-403271869

**Comment by l1t1** [comment]
nice job
