### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by ligan21** [Tencent/PhoenixGo#56]
在 centos 7 下，编译 phoeixGo 出现下面错误，是什么原因呢？
[root@VM_29_117_centos PhoenixGo]# bazel build //mcts:mcts_main
DEBUG: /root/.cache/bazel/_bazel_root/e348275a4d1fb6b530556d22a2214eb7/external/bazel_tools/tools/build_defs/repo/http.bzl:46:9: patch file //third_party/tensorflow:tensorflow.patch, path /root/PhoenixGo/third_party/tensorflow/tensorflow.patch
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: thread interrupted
INFO: Elapsed time: 109.216s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by wodesuck** [comment]
可能是网络问题？重试一下试试？

**Comment by ligan21** [comment]
用的腾讯云主机，国内网络是否要做相应处理？

**Comment by wodesuck** [comment]
我不太熟腾讯云，你试下能不能 wget 到 tf 的代码。

**Comment by ligan21** [comment]
试了很多次，总是下载不完tf，网络问题，能否提供一个能手动下载tf  的bazel 的编译方法。
