### ISSUE TITLE
window 下编译

### ISSUE THREAD

**Issue by ligan21** [Tencent/PhoenixGo#57]
visual studio 2017 编译 phoenixGo ，请问 pb 文件如何产生，能否把windows下的编译说明也提供一下

错误	C1083	无法打开源文件: “mcts\mcts_config.pb.cc”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	C:\Users\ligan\Source\Repos\PhoenixGo\c1xx	1	
错误	C1083	无法打开包括文件: “mcts/mcts_config.pb.h”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	c:\users\ligan\source\repos\phoenixgo\mcts\mcts_config.h	23	
错误	C1083	无法打开包括文件: “model/model_config.pb.h”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	c:\users\ligan\source\repos\phoenixgo\model\zero_model_base.h	25	
错误	C1083	无法打开源文件: “dist\dist_zero_model.pb.cc”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	C:\Users\ligan\Source\Repos\PhoenixGo\c1xx	1	
错误	C1083	无法打开源文件: “dist\dist_zero_model.grpc.pb.cc”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	C:\Users\ligan\Source\Repos\PhoenixGo\c1xx	1	
错误	C1083	无法打开源文件: “dist\dist_config.pb.cc”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	C:\Users\ligan\Source\Repos\PhoenixGo\c1xx	1	
错误	C1083	无法打开包括文件: “model/model_config.pb.h”: No such file or directory	C:\Users\ligan\Source\Repos\PhoenixGo\mcts_main.vcxproj	c:\users\ligan\source\repos\phoenixgo\model\zero_model_base.h	25

**Comment by wodesuck** [comment]
Windows 下编译有的麻烦。。
首先，你需要编译出一个 tensorflow，参考[这里](https://github.com/tensorflow/tensorflow/tree/v1.7.0/tensorflow/contrib/cmake)。
然后还要编译 glog，gflags 和 boost。
然后在 Visual Studio 里的“属性管理器”中，找到 ThirdPary 属性，双击打开它，找到“通用属性-用户宏”，填入上述依赖所在路径。
最后才能开始生成解决方案。

BTW，以上操作都需要在 Visual Studio 2015 下完成。经我测试，Visual Studio 2017 是编译不出 tensorflow 的。

**Comment by ligan21** [comment]
实测Visual Studio 2017 可以编译成功 TensorFlow。
请问PhoenixGo CPU 模式如何设置，TensorFlow 为NO GPU 模式，没有GPU库。

**Comment by ligan21** [comment]
mcts_main.vcxproj 文件中
   108：/WHOLEARCHIVE:tf_cc.dir\$(Configuration)\ tf_cc_ops.lib
   109:  /WHOLEARCHIVE:tf_core_direct_session.dir\$(Configuration)\tf_core_direct_session.lib 
   110:  /WHOLEARCHIVE:tf_core_ops.dir\$(Configuration)\tf_core_ops.lib   
   111: /WHOLEARCHIVE:tf_cc.dir\$(Configuration)\tf_cc.lib 
   112:  /WHOLEARCHIVE:tf_cc_ops.dir\$(Configuration)\tf_cc_ops.lib 

108 行的 tf_cc_ops.lib  是否应该是  tf_cc.lib.

**Comment by wodesuck** [comment]
111 行也有 tf_cc.lib 了，108 可能是多写了写错了，不改应该也不会有什么问题。

**Comment by ligan21** [comment]
不改，会报找不到文件。

**Comment by wodesuck** [comment]
那就删掉吧。在我这没问题。
