### ISSUE TITLE
How to compile PhoenixGo to the  x86 version? 

### ISSUE THREAD

**Issue by fmxFranky** [Tencent/PhoenixGo#64]
It seems like that the PhoenixGo can be compiled to the x86 version without tensorflow part. However, the struct of the project makes it very hard since that mcts_main also need tf or cuda lib etc.
So if there are some way to compile it to x86 version? Thanks a lot!

**Comment by wodesuck** [comment]
Not sure, possibly not. I think it won't success unless you could compile tensorflow to the x86 version.
