### ISSUE TITLE
Doesn't compile on local PC

### ISSUE THREAD

**Issue by GD-fix** [Tencent/PhoenixGo#67]
Doesn't compile (because that PC is local only) - I had downloaded zip archive and extracted its content. While bazel build:
    ERROR: error loading package...
(Tensorflow is installed).
How to compile on local PC (OS: openSUSE Tumbleweed)?

Thanks in advance.

**Comment by wodesuck** [comment]
Please provide more useful information (more logs).

**Comment by GD-fix** [comment]
I haven't with me log, but error is the same, as here: https://github.com/ymgaq/AQ/issues/85#issuecomment-399661625.
Is it necessary to give there exact log? Or there is a universal way to solve the problem?

P.S. Excuse me for my English.

**Comment by wodesuck** [comment]
I think it was a network issue. Bazel failed to download dependencies.

**Comment by GD-fix** [comment]
So, it's a true, that PhoenixGo doesn't compile on local only PC?

The log:

> Starting local Bazel server and connecting to it...
.......................................................
DEBUG: /home/tumbleweed/.cache/bazel/_bazel_tumbleweed/e64ddf2f03160574af1ea2d4784be7f7/external/bazel_tools/tools/build_defs/repo/http.bzl:51:5: patch file //third_party/tensorflow:tensorflow.patch, path /home/INSTall/0Go/LeelaZero/PhoenixGo-master/third_party/tensorflow/tensorflow.patch
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/v1.8.0.tar.gz] to /home/tumbleweed/.cache/bazel/_bazel_tumbleweed/e64ddf2f03160574af1ea2d4784be7f7/external/org_tensorflow/v1.8.0.tar.gz: Unknown host: github.com
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://github.com/tensorflow/tensorflow/archive/v1.8.0.tar.gz] to /home/tumbleweed/.cache/bazel/_bazel_tumbleweed/e64ddf2f03160574af1ea2d4784be7f7/external/org_tensorflow/v1.8.0.tar.gz: Unknown host: github.com
INFO: Elapsed time: 3.170s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by wodesuck** [comment]
Yes, you need network for downloading dependencies.

**Comment by GD-fix** [comment]
So, in zip archive there is no any reason...
