### ISSUE TITLE
是否仅支持19x19 标准盘？

### ISSUE THREAD

**Issue by arielly** [Tencent/PhoenixGo#70]
已经在 mac 下正常运行半年，代码肯定是能正常编译的。
1. 但是否仅支持19x19 标准盘，因为只要将 sabaki 调整成非 19 路棋盘，机器就无法落子，怀疑自带的权重文件(套用leela术语)仅针对19路盘，且让子必须为 6.5？
2. 这个和野狐围棋的绝艺是同一个东西么？

**Comment by OmnipotentEntity** [comment]
机器翻译。 我不说中文。 仅支持19x19板。 只支持一个komi。 这种限制是以这种方式设计的神经网络的典型。 我不知道野狐的具体情况。 但如果它像Alpha Go那样设计，那么它将分享这个限制。
