### ISSUE TITLE
Build fails on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by pepa65** [Tencent/PhoenixGo#71]
Following the readme, it fails after: `bazel build //mcts:mcts_main`
Error:
```
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/pp/git/PhoenixGo/tools/bazel.rc
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 0a95a46f-6f1e-4cb4-aa56-beebef8fcf23
ERROR: Analysis of target '//mcts:mcts_main' failed; build aborted: no such package '@boost//': The native new_http_archive rule is deprecated. load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive") for a drop-in replacement.
Use --incompatible_remove_native_http_archive=false to temporarily continue using the native rule.
INFO: Elapsed time: 29.515s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (5 packages loaded, 23 targets con\
figured)
    currently loading: @org_tensorflow//tensorflow
    Fetching @boost; fetching
```
* bazel release 0.20.0
* PhoenixGo git 1e88fb2f0b481ac8cdce7c88e547f7f3b9d99a9f
* python 3.6.7
* configured with only jemalloc-support (other options: N)

**Comment by wodesuck** [comment]
Try use bazel 0.11.1

**Comment by pepa65** [comment]
Thanks for the response. Sorry, I took the newest bazel but should have checked the readme better...

**Comment by pepa65** [comment]
Thanks for the response. Sorry, I took the newest bazel but should have checked the readme better...

**Comment by wonderingabout** [comment]
@pepa65 

you can use this all in one command : 

```sudo apt-get -y install pkg-config zip g++ zlib1g-dev unzip python git && git clone https://github.com/Tencent/PhoenixGo.git && cd PhoenixGo && wget https://github.com/bazelbuild/bazel/releases/download/0.17.2/bazel-0.17.2-installer-linux-x86_64.sh && chmod +x bazel-0.17.2-installer-linux-x86_64.sh && ./bazel-0.17.2-installer-linux-x86_64.sh --user && ./configure && bazel build //mcts:mcts_main && wget https://github.com/Tencent/PhoenixGo/releases/download/trained-network-20b-v1/trained-network-20b-v1.tar.gz && tar xvzf trained-network-20b-v1.tar.gz && sudo reboot```

**Comment by pepa65** [comment]
@wonderingabout Thanks for this. I got it to build. Now I am wondering how to use it. I tried it with Sabaki, but it never responded with a move. Is there a way to check it is working??
