### ISSUE TITLE
Why tensorRT does not support batch size higher than 4 ?

### ISSUE THREAD

**Issue by wonderingabout** [Tencent/PhoenixGo#75]
@wodesuck 
TensorRT 3.0.4 with cuda 9.0 cudnn 7.1.4 works no problem with batch size 4 on these 2 machines : 

machine 1 : 
- ubuntu 16.04
- ryzen r7 1700, 16gb ram, GTX 1060 6GB

machine 2 : 
- ubuntu 16.04
- Xeon Phi 2 cores/4 threads (cloud), 16gb ram, Tesla P100

But when i increase batch size for example to 8 (or any number which is 5 or more), the engine has a lot of errors and it does not work, reproduced on both of these machines

Example of errors : 
first : 
![tensor1v2](https://user-images.githubusercontent.com/38690718/50051443-76761500-0112-11e9-8954-60eb6904927f.png)

then after a few seconds : 
![tensor2v2](https://user-images.githubusercontent.com/38690718/50051457-e4224100-0112-11e9-8a85-306f17f381d0.png)

However, with batch size 4, tensorRT works good : 
![tensor3v3](https://user-images.githubusercontent.com/38690718/50051467-1d5ab100-0113-11e9-9ef7-ccc8a042e95d.png)

Also, when enable tensorRT is set to 0 (OFF),

batch sizes of 5 and more are supported again : 
For example here i set batch size to 48 (thinking time went down from 20s with batch size 4 tensorRT ON to 6.5s with batch size 48 tensorRT OFF for 4000 simulations per move) on tesla P100 : 

![tensor4](https://user-images.githubusercontent.com/38690718/50051552-fbfac480-0114-11e9-8805-913d75e2cd30.png)
![tensor5](https://user-images.githubusercontent.com/38690718/50051562-2cdaf980-0115-11e9-90ef-a7ac0ab83d23.png)

And here with batch size 64 tensorRT OFF on tesla P100 : 

![tensor8](https://user-images.githubusercontent.com/38690718/50051575-52680300-0115-11e9-9cec-5aac553a8001.png)
![tensor9](https://user-images.githubusercontent.com/38690718/50051582-6b70b400-0115-11e9-92ed-24ba43491609.png)

Note :  without tensorRT, batch size are supported even up to 64 and more (has been tested on Windows 10 with a Tesla V100 successfully)
Increasing batch size to 8 has the same effect on speed improvement than tensorRT enabled at batch size 4
Of course, batch size 16,32,64 with tensorRT OFF are much faster to compute games than batch size 4 with tensorRT ON

So, any plans to improve the software ?
thanks

**Comment by wonderingabout** [comment]
so, what should i do if i want to use tensorRT with batch size 32 for example ?

**Comment by wodesuck** [comment]
I have released some tools, `git pull` then,
`bazel build //model:build_tensorrt_model`
build tensorrt model with command
`scripts/build_tensorrt_model.sh $dir $ckpt $batch_size`
e.g. `scripts/build_tensorrt_model.sh ckpt zero.ckpt-20b-v1 4`

Note that you need TensorRT installed (`.so` and python `.whl` module).

**Comment by wonderingabout** [comment]
OK great !

i will try to do this and tell you how it goes

**Comment by wonderingabout** [comment]
update : 

i did not have time to try it today, i will try tomorrow i hope

**Comment by wonderingabout** [comment]
it's likely that i will still be busy today (writing a long tutorial for gtp2ogs), but since i only have little experience about python it is likely that i will have some difficulties

can you provide me the main steps starting from a clean ubuntu install 16.04, that has only installed cuda 9.0, cudnn 7.1.4, tensorrt 3.0.4, bazel 0.11.1 (phoenixgo tested to work successfully), and nothing more ?

i can manage the details i think, but i would like a few guidelines on the main steps

big thanks @wodesuck 

other question : 
any plans to support latest versions of tensorflow ? (mainly for tesla v100 and p100 best support)
- version 5.0 : tensorflow to tensorrt model export requires tensorflow 1.9
- version 4.0 : tensorflow to tensorrt model export requires tensorflow 1.8
- version 3.0 : tensorflow to tensorrt model export requires tensorflow 1.3

i didnt try tensorrt 4.0 or 5.0 yet, but i assume 5.0 will not work because it's superior to 1.8. It would be great if you could update for tensorrt 5.0

**Comment by wonderingabout** [comment]
update : 

the contribution that i was doing for OGS website has been finished : 
it is featuring PhoenixGo : 

https://docs.google.com/document/d/1BsZq980zOX02g34ElwOo3Ec1BiD7tGZYZQfKF73GGUU/edit#

it will also be available on a separate github

I hope that tomorrow i will have time to try these steps now

**Comment by wonderingabout** [comment]
update : 

the contribution that i was doing for OGS website has been finished : 
it is featuring PhoenixGo : 

i will put the link here when i finish exporting it to github

it will also be available on a separate github

I hope that tomorrow i will have time to try these steps now

**Comment by wonderingabout** [comment]
update 2 : 
the github export that took me a lot of time is finally available here, it features PhoenixGo @wodesuck so you may consider linking : https://github.com/wonderingabout/gtp2ogs-tutorial

i hope that tomorrow i will finally ! be able to try to build batch size 32 with tensorrt

**Comment by wonderingabout** [comment]
update : 

i still didnt forget about that but i need time to try it

also, i most likely will need help of what to do to install the prerequirement packages and settings

**Comment by wonderingabout** [comment]
update 2 : 

after doing some reading, if i understand it well i need to install cuda with tar install and then tensorrt with tar install too, then export python path and install .whl

i found helpful documentation here (just need to slightly modify for tensorrt 3.0.4) : https://kezunlin.me/post/dacc4196/

then i'll start with a new system and rebuild bazel too

this is the issue i had in my current system after running `sudo pip2 install tensorrt-3.0.4-cp27-cp27mu-linux_x86_64.whl` in /opt/tensorrt/python (path where is extracted the tar of tensorrt 3.0.4)

**Comment by wonderingabout** [comment]
update @wodesuck 

i have succeeded to install pycuda now

actually, run install of cuda was not needed (and is not recommended by nvidia),
but after `sudo apt-get install cuda-9.0` **my mistake was that i had not installed `sudo apt-get install nvidia-cuda-toolkit`**

i avoided to install this last package because some websites said it was not recommended, and phoenixgo can run without this package so i didnt bother much with it, however it was needed for pycuda

summary : 
on a brand new ubuntu 16.04 
(do not install nvidia-384, it is included in cuda-9.0)
all steps followed from here : https://medium.com/@mishra.thedeepak/cuda-and-cudnn-installation-for-tensorflow-gpu-79beebb356d2

- deb install of cuda-9.0
- then apt-get install cuda-9.0
**- then apt-get install nvidia-cuda-toolkit**
- then deb install of cudnn 7.0.5 (as recommended by nvidia pdf)
- then path exports of cuda
- then path export of tensorrt 3.0.4 (tar file), all steps from here : https://kezunlin.me/post/dacc4196/ , there is also a copy in my repo : https://kezunlin.me/post/dacc4196/
- then tar install of tensorrt 3.0.4 (tar file)
- then install of .whl (pycuda) with pip (python2)
- then i will update the rest of the steps later when i finish it

i will continue the

**Comment by wonderingabout** [comment]
now that this issue is solved, extra comments : 

too bad that i forgot to set intel skylake on google cloud (avx2 and avx512f were disabled because of that, need to rebuild, will update when i do)

i also updated the instructions in my personal repo : https://github.com/wonderingabout/nvidia-archives 

will update the pull request with this new data on tensorrt custom max batch size and how to do it

last question : does phoenixgo support tensorrt 5.0 ? (i read that tensorflow 1.9 is needed for the export model to tensorrt in nvidia docs)

**Comment by wonderingabout** [comment]
indeed, pycuda needs to be installed separately, not following the nvidia instructions

first create cuda.h file in etc/profile.d as explained here and add cuda-9.0 path in it : 
then add the path for root in .bashrc and source ~/.bashrc
then `sudo su -`
then `cd /opt/tensorrt/python`
then `pip install pycuda`
then after pycuda is installed follow nvidia instructions to install the .whl of tensorrt : `pip install --upgrade tensorrt-3.0.4-cp27-cp27mu-linux_x86_64.whl`
then pip install the uff .whl
then compile a sample and run it : 
result : 
![pycuda at last](https://user-images.githubusercontent.com/38690718/50451781-70fca400-0936-11e9-86d7-0c5b2b6adb2e.png)

**Comment by wonderingabout** [comment]
tensorrt batch size 4
tensorrt batch size 32
tensorrt batch size 16

![last](https://user-images.githubusercontent.com/38690718/50454261-a4dfc580-0946-11e9-8457-228c19c64834.png)
