### ISSUE TITLE
.cache folder is big : 6.1 GB after building : cleanup possible ?

### ISSUE THREAD

**Issue by wonderingabout** [Tencent/PhoenixGo#76]
after the building is finished, .cache is not cleaned and it is big

6.1 GB on my computer

![cache cleanup](https://user-images.githubusercontent.com/38690718/50371965-7324d280-05c5-11e9-855c-bd368278198a.png)

however, windows and mac binaries are much smaller, so i assume a lot of cleanup is possible on linux

what is the folders that can be safely removed in .cache and in PhoenixGo folders ?

thanks
@wodesuck

**Comment by wodesuck** [comment]
`bazel clean`

**Comment by wonderingabout** [comment]
thanks :)

i gained 1.3 GB, which is still worth taking : 


![bazelafter](https://user-images.githubusercontent.com/38690718/50386235-61d1e800-06e3-11e9-8650-81194f65bc38.png)
![beforebazel](https://user-images.githubusercontent.com/38690718/50386236-626a7e80-06e3-11e9-8d89-fe80dc108af6.png)
![after bazelv2](https://user-images.githubusercontent.com/38690718/50386234-61d1e800-06e3-11e9-985e-6e47060fe938.png)

i guess i should rebuild with disabling all the options i dont need during the bazel  build (google cloud, android workspaces, etc...)

**Comment by wonderingabout** [comment]
should i add a faq question for that ?

**Comment by wonderingabout** [comment]
update : 

it seems the `bazel clean` broke the engine

i'll rebuild to see (i'll also use this opportunity to remove the huge .cache bazel folder and build only what i need)

![enginebroken](https://user-images.githubusercontent.com/38690718/50387058-2db2f300-06f4-11e9-84f9-387bc30b9c5c.png)

**Comment by wodesuck** [comment]
You should backup the binary and library you just built (`mcts_main` and `libtensorflow_framework.so`) before cleanup.

**Comment by wonderingabout** [comment]
update : 

i backed up `mcts_main` , `libtensorflow_framework.so` , and just in case i backed up all the /PhoenixGo/bazel-bin/_solib_local/ folder entirely too

then i copied `mcts_main` and `libtensorflow_framework.so` in mcts folder, and also `libtensorflow_framework.so` in ~\PhoenixGo\ , but i get the following error

![phoenixgo7](https://user-images.githubusercontent.com/38690718/50395390-e3695a80-0763-11e9-9275-892eaa0ae8c2.png)

but i get this error : 

where should i copy the `libtensorflow_framework.so` file (i tried all existing directories with same error)

and second question : does `bazel clean` remove the possibility to build later with batch size 32 ? (as we saw in #75 )

thanks

**Comment by wonderingabout** [comment]
update : i found that bazel-bin folder is a link to this place : 

![bazelbin location](https://user-images.githubusercontent.com/38690718/50471056-5ae0f900-09b3-11e9-9631-6c2a831deb3e.png)


i will try to backup the original files then run `bazel clean` again, then recreate their original tree in .cache

**Comment by wonderingabout** [comment]
update : i increased the size of my ubuntu parition, and although its interesting, 3GB is not big now, 

i rebuilt phoenixgo again, so i will not try this anytime soon
if someone does, update this thread or start another then
