### ISSUE TITLE
PyCUDA ubuntu custom max batch size : I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

### ISSUE THREAD

**Issue by wonderingabout** [Tencent/PhoenixGo#77]
related to #75 here : https://github.com/Tencent/PhoenixGo/issues/75#issuecomment-449856241

in order to have higher max batch size, 
i install tensorflow-gpu with pip install (`/usr/bin/python: No module named tensorflow.python.tools` are needed so i have to install tensorflow)

![error3](https://user-images.githubusercontent.com/38690718/50486682-593b2380-09fb-11e9-91c1-6ea7ba2f2d7a.png)

so after the pip install of tensorflow-gpu, i try to build the tensor model with batch size 32, however the tensorflow binary built doesnt support avx2 and fma

> I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

**however there is no such message when starting the engine (even with `--logtostderr`) , so it is an issue related to how i built the tensor model (set max batch size to 32)**

![tensorflow avx2 fma](https://user-images.githubusercontent.com/38690718/50485919-8be31d00-09f7-11e9-88c3-dc0d535da91e.png)

in a game, no problem even with `--logtostderr`

![problem2](https://user-images.githubusercontent.com/38690718/50486329-cc439a80-09f9-11e9-87c0-0ef098842837.png)

how can i use max batch size 32 without losing the avx2 and fma instructions ?

thanks

**Comment by wonderingabout** [comment]
@wodesuck 

please tell me when your windows build including avx avx2 fma instructions is ready

i sometimes run PhoenixGo on a go server on my windows machine (not always ubuntu), so i really need it
big thanks

**Comment by l1t1** [comment]
can you complie it by youself

**Comment by wonderingabout** [comment]
@l1t1 

i use windows rarely so no

@wodesuck was planning to do it, hopefully quite soon

**Comment by wonderingabout** [comment]
closing as it is stale

i hope someone will look at that again someday
