### ISSUE TITLE
[Feature Request] Provide a way to build on Windows using Bazel

### ISSUE THREAD

**Issue by guikarist** [Tencent/PhoenixGo#79]
Now that there is a pre-built binary of PhoenixGo on Windows, it is very kind of you to provide a way to build PhoenixGo on Windows **using Bazel**.

* It will be helpful for us to learn by modifying your codes.
* Now Bazel supports Windows, and the building process using Bazel is very convient compared to using Visual Studio.

**Comment by wonderingabout** [comment]
hi,

i would also be interested in a bazel compile for windows (that would also fix the avx avx2 fma avx512 issue here #74 )

however that probably requires some work to implement if it is ever possible

@wodesuck @fiskerhuang @funionguo know better (i am only a contributor)

**Comment by wonderingabout** [comment]
@guikarist i dont know :)
we need to ask the names i mentionned in first message

**Comment by wodesuck** [comment]
I have try, but: 1. failed to use http_archive with `patch` parameter, 2. failed to build glog with bazel.
Need some modify for building with bazel on windows.

**Comment by guikarist** [comment]
@wodesuck Thanks for response. I have encountered the first problem, too. On Windows, MSYS2 is used for Bazel, so the code to run patch binary should be stripped of `/usr/bin/` (the `$PATH` environment variable should be correctly set). I am planning to learn more about Bazel and make some modifications to Bazel files in PhoenixGo. However now I am not completely aware of what the building process of PhoenixGo really is.

**Comment by wonderingabout** [comment]
@wodesuck 

yes, most likely some building settings need to be modified

if you manage to build with bazel on windows, that would solve many issues, and most of all that would be a great achievement (using bazel is so easy on powerful)

**Comment by guikarist** [comment]
@wonderingabout

Thanks. My colleague has done this before. But it is obviously not simple and can only support Tensorflow which is built by CMake. And Tensorflow doesn’t support CMake since 1.11.

Now I have succeeded in [building `libtensorflow_cc.so` on Windows using Bazel](
https://github.com/guikarist/tensorflow-windows-build-script) which can be used after being renamed to `libtensorflow_cc.dll`. But other third-party lib files have `.a` extensions instead of `.lib`. There must be some problems in building Tensorflow on Windows using Bazel, too. However, I believe one day they would be solved!

**Comment by wonderingabout** [comment]
i hope too @guikarist 

can you compile using visual studio 2015 rather then ?

it would be very great to have a version with : 

- cuda 10.0 (already works on ubuntu, i tested it)
- cudnn 7.4.2 (same)
- supports avx avx2 fma (to cover most modern home cpu)

**Comment by wonderingabout** [comment]
pity or not, i would appreciate if you provide a new release

the old one is so outdated and slow :sob:

**Comment by wonderingabout** [comment]
@guikarist pity or not, i would appreciate if you provide a new release

the old one is so outdated and slow :sob:

**Comment by guikarist** [comment]
@wonderingabout No problem, my colleague will do this and I will send you one as soon as he finishes.

**Comment by guikarist** [comment]
@wodesuck 

Now Tensorflow C++ API on Windows can be built but the output files have `.so` or `.a` extensions.

The `libtensorflow_cc.so` file can be renamed to `libtensorflow_cc.dll`, and used correctly *to some extent*. But I have no idea how to use the built third-party files which have `.a` files. Do you think whether it is possible to work out a way to build PhoenixGo using Bazel with current version of Tensorflow?

**Comment by wonderingabout** [comment]
@guikarist 

great !!
i cant wait really

this is the biggest highlights needed for a new windows release : 

it would be very great to have a version with :

- cuda 10.0 (already works on ubuntu, i tested it)
- cudnn 7.4.2 (same)
- support for avx avx2 fma (to cover most modern home cpu)**

cuda 10.0 would support turing GPU (RTX cards), and will improve performance on Volta cards (tesla V100, titan V, etc...,), as well as improve performance on all cards

cudnn 7.4.x is significantly faster than the old cudnn 7.1.x

avx avx2 fma cpu instructions are still lacking atm, which makes the computation a lot slower

@guikarist 
when your release is finished i'll test it, and if it works well i'll add it to the releases on my PR (consider sending a pull request to my branch so that you get credit for it)

**Comment by wonderingabout** [comment]
@guikarist 

on ubuntu bazel always downloads tensorflow 1.8

i assume it is not yet compatible with tensorflow 1.9+ (but try, maybe you can)
@wodesuck knows better than me

**Comment by guikarist** [comment]
@wonderingabout @wodesuck 
[This issue in Tensorflow](https://github.com/tensorflow/tensorflow/issues/24885) may be important for your work.

@wonderingabout 
My colleague is working on building a release of PhoenixGo at the moment.

**Comment by wonderingabout** [comment]
@guikarist i'm sure this will be greatly helpful for @wodesuck who manages the code, i read the main general lines, big thanks for your contribution on tensorflow for windows ! :+1: 

building on bazel is the ultimate ideal distant goal

the main priority atm is to get a new release for windows no matter how it is built (visual studio or bazel)

if i can help in any way i'd be glad
big thanks for your effort !! keep me updated how it goes :+1: @guikarist

**Comment by guikarist** [comment]
@wonderingabout My pleasure! We had been trying buiding with Bazel. What we did with CMake is something one year ago. So it may need time for my colleague to do this.

**Comment by wonderingabout** [comment]
oh i understand, thanks for the feedback :+1:  @guikarist 

then i guess its natural to go with cuda 9.0 instead, with cudnn 7.4.2, and the support of all modern cpu instructions in home computers (avx, avx2, fma), thta the existing build doesnt support

can you gather the data about the various issues you encountered and their fixes, it may be helpful for other people in the future

thanks again !

i'd like if you build with cuda 9.0 and the other settings i mentionned :100:

**Comment by wonderingabout** [comment]
@guikarist 

any update or news on the basic compilation for windows ?
so that most windows users can enjoy the basic avx avx2 fma cpu instructions :+1:  (and cuddn 7.4.2 + cuda 9.0)

it would be really a very big help

**Comment by guikarist** [comment]
Sorry to have kept you waiting. My colleague hasn't worked out, and I will have a try soon.

**Comment by wonderingabout** [comment]
maybe this can be given another try some future time, but thanks for the effort anyways :+1:
