### ISSUE TITLE
Cannot build with bazel 0.13

### ISSUE THREAD

**Issue by aviczhl2** [Tencent/PhoenixGo#8]
ERROR: .cache/bazel/_bazel_/f0defbf128b2eb9b315d11754028a380/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
ERROR: Analysis of target '//mcts:mcts_main' failed; build aborted:

.cache/bazel/_bazel_/f0defbf128b2eb9b315d11754028a380/external/jpeg/BUILD:126:12: Illegal ambiguous match on configurable attribute "deps" in @jpeg//:jpeg:
@jpeg//:k8
@jpeg//:armeabi-v7a
Multiple matches are not allowed unless one is unambiguously more specialized.
INFO: Elapsed time: 78.411s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (61 packages loaded)

On Ubuntu 16.04
Linux version 4.4.0-92-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) )

**Comment by wodesuck** [comment]
Bazel may not be backward compatible, try bazel 0.11.1 which is known-good

**Comment by godmoves** [comment]
This is an issue of tensorflow, bazel 0.12 and 0.13 are not supported.
