### ISSUE TITLE
are you understand chinese? i am a Go player，Your software is not human enough.

### ISSUE THREAD

**Issue by zhouqiw** [Tencent/PhoenixGo#83]

**Comment by zhouqiw** [comment]
每次悔棋时都要重新从第一步开始算胜率，导致效率不高，导致出结果较慢，请改进

**Comment by wonderingabout** [comment]
hi,

you can start the game at a custom start position : 

use : 

 `--init_moves` (Initialize Go board with init_moves.) type: string default: ""

you can find the state of the previous game in  : 

```
Jan 16 18:21:23 !!!!! [16812] stderr: I0116 18:21:23.238700 16812 mcts_engine.cc:152] Move: dp,zz,qe,zz,dd,qp,zz,qg,zz,pc,oq,pn,od,pd,pe,oe,of,ne,pg,md,pi,cc,dc,cd,cf,ce,de,bf,cb,bb,be,ae,bg,bd,lc,nf,nc,mc,mb,nb,ob,lb,na,kc,oc,pb,qd,rb,rc,pa,qc,qb,sb,la,ra,df,cg,ef,gd,dj,cj,ee,fc,ci,dk,ei,dh,di,ck,bj,eh,fh,fg,eg,ld,le,kd,jb,gh,fi,ff,ch,jd,ma,oa,nb,qa,hc,ie,gb,fe,ed,ec```

for example : 

`--init_moves="dp,zz,qe,zz,dd,qp,zz,qg,zz,pc,oq,pn,od,pd,pe,oe,of,ne,pg,md,pi"`

you can see a help of possible commands here : 
https://github.com/wonderingabout/PhoenixGo/blob/faqv2-bazel-master/docs/mcts-main-help.md

**Comment by wonderingabout** [comment]
@zhouqiw

**Comment by wodesuck** [comment]
support `undo` command in [this commit](https://github.com/Tencent/PhoenixGo/commit/55dba6b572a1f5098ae723557184721703e96011).

**Comment by wonderingabout** [comment]
i will add that to the documentation in a new PR, i hope this will be useful (at least its faster than copy paste list of all previous moves and start a new game) @wodesuck

**Comment by wonderingabout** [comment]
added in #90
