### ISSUE TITLE
Policy network value

### ISSUE THREAD

**Issue by pnprog** [Tencent/PhoenixGo#87]
Dear PhoenixGo team,

I would like to collect some information about PhoenixGo moves **policy network** values. Are those values displayed into the log?

**Comment by wodesuck** [comment]
Yes.
<pre>
1th move(b): dp, winrate=44.110905%, N=654, Q=-0.117782, <b>p=0.079232</b>, v=-0.116534
</pre>
`p` is the policy network values.

**Comment by pnprog** [comment]
Thanks for the answer!
